export { default as Header } from "./Header/Header";
export { default as Hero } from "./Hero/Hero";
export { default as Corruption } from "./Corruption/Corruption";
export { default as CorruptionContainer } from "./CorruptionContainer/CorruptionContainer";
export { default as CounteractContainer } from "./CounteractContainer/CounteractContainer";
export { default as Counteract } from "./Counteract/Counteract";
export { default as Footer } from "./Footer/Footer";
export { default as Button } from "./Button/Button";
export { default as Error } from "./Error/Error";
